# Generated by Django 3.0.5 on 2020-05-05 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_medicalcard_medication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='trekkhundreg_id',
            new_name='trekkhundreg',
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='dosage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
