# Generated by Django 3.0.5 on 2020-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_auto_20200507_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='location',
            field=models.CharField(blank=True, choices=[('a_poll', 'A poll'), ('b_poll', 'B poll'), ('c_poll', 'C poll'), ('d_poll', 'D poll'), ('racing', 'Racing'), ('out', 'Out')], max_length=8),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='diagnosis_long',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='diagnosis',
            field=models.CharField(max_length=30),
        ),
    ]
