# Generated by Django 3.0.5 on 2020-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0006_auto_20200508_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='location',
            field=models.CharField(blank=True, choices=[('a_pool', 'A pool'), ('b_pool', 'B pool'), ('c_pool', 'C pool'), ('d_pool', 'D pool'), ('racing', 'Racing'), ('out', 'Out')], max_length=8),
        ),
    ]
